name: Build, Test, Lint, and SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v7
      with:
        dotnet-version: 6.0.100

    - name: Restore dependencies
      run: dotnet restore

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v7
      with:
        dotnet-version: 6.0.100

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

  lint:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run linting
      # Add your linting commands here

  sonarcloud:
    runs-on: ubuntu-latest

    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v7
      with:
        dotnet-version: 6.0.100

    - name: Run SonarCloud analysis
      run: |
        dotnet sonarscanner begin /k:"BitsDevOpsGrp17" /d:sonar.login="${{ secrets.SONARCLOUD_TOKEN }}" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
        dotnet build
        dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONARCLOUD_TOKEN }}"

env:
  SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

