name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Run Tests
      run: dotnet test --no-build --configuration Release

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format --version 5.0.1

    - name: Format code
      run: dotnet format --check

    - name: Analyze code
      run: dotnet analyze

    - name: Check for changes
      id: check_changes
      run: echo ::set-output name=changes::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

  sonarcloud:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Java for SonarCloud Analysis
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Install SonarCloud Scanner
      run: |
        dotnet tool install --global dotnet-sonarscanner
        export PATH="$PATH:/root/.dotnet/tools"

    - name: Run SonarCloud Analysis
      run: |
        dotnet sonarscanner begin /k:"sarkasou_BitsDevOpsGrp17" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.dotcover.reportsPaths="**/*.dotcover" /d:sonar.host.url="https://sonarcloud.io" /o:"sarkasou"
        dotnet build --configuration Release
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
